config/routes.rb
Downcheck::Application.routes.draw do

  get "contact_us/show_page"
  get "about_us/show_page"
  get "landing/index"

  resources :checks
  resources :check_datum

  devise_for :users

  root to: 'landing#index'

  get 'contact' => 'contact_us#show_page'
  get 'about' => 'about_us#show_page'

  get 'results/:check_id' => 'check_data#index'
  get 'results' => 'check_data#index'

  

end

app/models/check.rb
class Check < ActiveRecord::Base
    belongs_to :user
    has_many :check_datum

    def Check.get_checks_to_run_every_minute_interval(minute_interval)
        self.where("minute <= ?", minute_interval)
    end
end

app/controllers/checks_controller.rb
class ChecksController < ApplicationController
  before_action :set_check, only: [:show, :edit, :update, :destroy]

  # GET /checks
  # GET /checks.json
  def index
    authorize_user!
    @checks = Check.all
  end

  # GET /checks/1
  # GET /checks/1.json
  def show
  end

  # GET /checks/new
  def new
    authorize_user!
    @check = Check.new
  end

  # GET /checks/1/edit
  def edit
    authorize_user!
  end

  # POST /checks
  # POST /checks.json
  def create
    authorize_user!
    @check = Check.new(check_params)
    @check.user_id = current_user.id

    respond_to do |format|
      if @check.save
        format.html { redirect_to @check, notice: 'Check was successfully created.' }
        format.json { render action: 'show', status: :created, location: @check }
      else
        format.html { render action: 'new' }
        format.json { render json: @check.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /checks/1
  # PATCH/PUT /checks/1.json
  def update
    authorize_user!
    respond_to do |format|
      if @check.update(check_params)
        format.html { redirect_to @check, notice: 'Check was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @check.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /checks/1
  # DELETE /checks/1.json
  def destroy
    authorize_user!
    @check.destroy
    respond_to do |format|
      format.html { redirect_to checks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_check
      @check = Check.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def check_params
      params.require(:check).permit(:name, :url, :minute,)
    end
end

app/helpers/checks_helper.rb
module ChecksHelper
end

app/views/checks/_form.html.erb
<%= form_for(@check) do |f| %>
    <% if @check.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@check.errors.count, "error") %> prohibited this check from being saved:</h2>
            <ul>
                <% @check.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="form-group">
        <%= f.label :name %>
        <%= f.text_area :name, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :url %>
        <%= f.text_area :url, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= f.label "Interval" %>
        <%= f.select :minute, 
                    [["1 Minutes","1"], ["5 Minutes","5"], 
                    ["15 Minutes","15"],["60 Minutes","60"]], {}, {class: "form-control"} %>
    </div>
    <div class="checkbox">      
        <label>
            <%= f.check_box :notify %> Notify When Down
        </label>
    </div>

    <div class="actions">
        <%= f.submit class: "btn btn-lg btn-primary btn-block" %>
    </div>
<% end %>

app/views/checks/edit.html.erb
<h1>Editing check</h1>

<%= render 'form' %>

<%= link_to 'Show', @check %> |
<%= link_to 'Back', checks_path %>

app/views/checks/index.html.erb
<h1 class='page-title'>Checks</h1>

<div class='table-responsive'>
    <table class='data-table table table-hover'>
      <thead>
        <tr>
          <th>Name</th>
          <th>Url</th>
          <th>Interval</th>
          <th colspan=3>Actions</th>
        </tr>
      </thead>

      <tbody>
        <% @checks.each do |check| %>
          <tr>
            <td><%= check.name %></td>
            <td><%= check.url %></td>
            <td><%= check.minute %></td>
            <td><%= link_to 'Results', 'results/'+check.id.to_s %><br>
             </td>
            <td><%= link_to 'Edit', edit_check_path(check) %></td>
            <td><%= link_to 'Destroy', check, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
</div>

<%= link_to 'New Check', new_check_path %>

app/views/checks/new.html.erb
<h1 class='page-title'>New check</h1>

<%= render 'form' %>

<%= link_to 'Back', checks_path %>

app/views/checks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @check.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @check.url %>
</p>

<p>
  <strong>Interval:</strong>
  <%= @check.minute %>
</p>

<%= link_to 'Edit', edit_check_path(@check) %> |
<%= link_to 'Back', checks_path %>