config/routes.rb
Downcheck::Application.routes.draw do

  get "contact_us/show_page"
  get "about_us/show_page"
  get "landing/index"

  resources :checks
  resources :check_datum

  devise_for :users

  root to: 'landing#index'

  get 'contact' => 'contact_us#show_page'
  get 'about' => 'about_us#show_page'

  get 'results/:check_id' => 'check_data#index'
  get 'results' => 'check_data#index'

  

end

app/controllers/check_data_controller.rb
class CheckDataController < ApplicationController
  before_action :set_check_datum, only: [:show, :edit, :update, :destroy]

  # GET /check_data
  # GET /check_data.json
  def index
    authorize_user!
    if(params[:check_id])
        @check_data = CheckDatum.where(check_id: params[:check_id]).order(date_checked: :desc)
        check = Check.find(params[:check_id])
      @check_name = check.name
    else
      @check_name = "All Recent Checks"
      @check_data = CheckDatum.all.order(date_checked: :desc)
    end
  end

  # GET /check_data/1
  # GET /check_data/1.json
  def show
    if(!user_signed_in?) 
     flash[:notice] = 'You need to sign in first' 
     redirect_to new_user_session_path
    else
     flash[:notice] = 'You need to sign in first asrsdfa' 
     redirect_to new_user_session_path
    end
  end

  # GET /check_data/new
  def new
    @check_datum = CheckDatum.new
  end

  # GET /check_data/1/edit
  def edit
  end

  # POST /check_data
  # POST /check_data.json
  def create
    @check_datum = CheckDatum.new(check_datum_params)

    respond_to do |format|
      if @check_datum.save
        format.html { redirect_to @check_datum, notice: 'Check datum was successfully created.' }
        format.json { render action: 'show', status: :created, location: @check_datum }
      else
        format.html { render action: 'new' }
        format.json { render json: @check_datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /check_data/1
  # PATCH/PUT /check_data/1.json
  def update
    respond_to do |format|
      if @check_datum.update(check_datum_params)
        format.html { redirect_to @check_datum, notice: 'Check datum was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @check_datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /check_data/1
  # DELETE /check_data/1.json
  def destroy
    @check_datum.destroy
    respond_to do |format|
      format.html { redirect_to check_data_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_check_datum
      @check_datum = CheckDatum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def check_datum_params
      params.require(:check_datum).permit(:date_checked, :check_id, :status, :response_time)
    end
end

app/helpers/check_data_helper.rb
module CheckDataHelper
end

app/views/check_data/_form.html.erb
<%= form_for(@check_datum) do |f| %>
  <% if @check_datum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@check_datum.errors.count, "error") %> prohibited this check_datum from being saved:</h2>

      <ul>
      <% @check_datum.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date_checked %><br>
    <%= f.datetime_select :date_checked %>
  </div>
  <div class="field">
    <%= f.label :check_id %><br>
    <%= f.number_field :check_id %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :response_time %><br>
    <%= f.number_field :response_time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/check_data/edit.html.erb
<h1>Editing check_datum</h1>

<%= render 'form' %>

<%= link_to 'Show', @check_datum %> |
<%= link_to 'Back', check_data_path %>

app/views/check_data/index.html.erb
<h1 class='page-title'>Check History for <%= @check_name %></h1>

<div class='table-responsive'>
    <table class='data-table table table-hover'>
        <thead>
            <tr>
                <th>Date</th>
                <th>Time</th>
                <th>Status</th>
                <th>Response time</th>
            </tr>
        </thead>

        <tbody>
            <% @check_data.each do |check_datum| %>
            <tr>
                <td><%= check_datum.date_checked.to_date %></td>
                <td><%= check_datum.date_checked.strftime("%I:%M:%S") %></td>
                <td><%= check_datum.status %></td>
                <td><%= check_datum.response_time %> ms</td>
            </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/check_data/new.html.erb
<h1>New check_datum</h1>

<%= render 'form' %>

<%= link_to 'Back', check_data_path %>

app/views/check_data/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date checked:</strong>
  <%= @check_datum.date_checked %>
</p>

<p>
  <strong>Check:</strong>
  <%= @check_datum.check_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @check_datum.status %>
</p>

<p>
  <strong>Response time:</strong>
  <%= @check_datum.response_time %>
</p>

<%= link_to 'Edit', edit_check_datum_path(@check_datum) %> |
<%= link_to 'Back', check_data_path %>